AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*

Documentation:
  Exclude:
    - spec/**/*

MethodLength:
  Max: 15

StringLiterals:
  EnforcedStyle: double_quotes
